sudo: required
language: node_js
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - echo sha = $SHA
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project course-k8s
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - cd client && npm i
  # - docker build -t bitofant/react-test -f ./client/Dockerfile.dev ./client
  - bash ./build.sh

scripts:
  - docker run bitofant/multi-client npm test -- --coverage

# scripts:
#   - npm run test

# scripts:
#   - cd client && npm test --coverage

# scripts:
#   - docker run bitofant/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master